#!/bin/bash
# This is a short script that will copy a file template 
# for the user to the desired location. 
#
# Not the prettiest script, but it does the job.
#
# Created by Jamie Bodeau on 11/29/2017

# Customization variables --------------------------------

username="Jamie Bodeau"

# Templates ----------------------------------------------

usage=$(cat<<EOF
Usage Method 1: template [filename].[extension]
Usage Method 2: template [flags] [template name] [filename]
Flags:
    -h  help message
Template options:
    py      Python
    cpp     C++
    c       C
EOF
)

pythonPath="/usr/bin/env python"
py=$(cat<<EOF
#!$pythonPath
# $username

# Imports -------------------------------------------------

import sys

# Classes -------------------------------------------------



# Functions -----------------------------------------------



# Main Execution ------------------------------------------

if __name__ == "__main__":
    for line in sys.stdin:
        print line
EOF
)

cpp=$(cat<<EOF
// $username

// Headers -----------------------------------------------

#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
using namespace std;

// Prototypes --------------------------------------------



// Main Execution ----------------------------------------

int main(int argc, char** argv){

    // Exit main
    return EXIT_SUCCESS;
}

// Functions ---------------------------------------------
EOF
)

c=$(cat<<EOF
// $username

// Headers -----------------------------------------------

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// Prototypes --------------------------------------------



// Main Execution ----------------------------------------

int main(int argc, char** argv){

    // Exit main
    return EXIT_SUCCESS;
}

// Functions ---------------------------------------------
EOF
)

# Functions ----------------------------------------------

print_usage(){
   cat <<< "$usage" 
}


copy_template(){
    if [ $# -gt 1 ]; then
        template=$1
        destination=$2
        cat <<< "$template" > "$destination"
    else
        echo "Error in copy_template: Not enough args"
    fi
}


# Main Execution -----------------------------------------

# Make sure we have some arguments
if [ $# -lt 1 ]; then
    print_usage
    exit 1
fi

# Complete action
case "$1" in
    # Python -----------------------
    py) 
        echo Copying python template.
        copy_template "${py}" "$2"
        chmod u+x "$2"
        ;;

    *.py)
        echo Copying python template.
        copy_template "${py}" "$1"
        chmod u+x "$1"
        ;;

    # C++ ---------------------------
    cpp)
        echo Copying C++ template.
        copy_template "${cpp}" "$2"
        ;;
    
    *.cpp)
        echo Copying C++ template.
        copy_template "${cpp}" "$1"
        ;;

    # C -----------------------------
    c)  
        echo Copying C template.
        copy_template "${c}" "$2"
        ;;
    
    *.c)
        echo Copying C template.
        copy_template "${c}" "$1"
        ;;
    
    # Default -----------------------
    *)  print_usage
        exit 1
        ;;
esac

# Success
exit 0










